name: fed-cbm
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pytorch::pytorch=2.1.*
  - torchvision=0.16.*
  - networkx
  - lightning
  - cdt
  - fpdf2
  - requests
  - python-dotenv
  - hydra-core=1.3.*
  - numpy<2
  - pandas
  - tqdm
  - scipy
  - scikit-learn
  - openpyxl
  - huggingface_hub
  - pyg::pyg
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - flwr
  - sentence-transformers
  - pip
  - pip:
    - wandb
    - plotly
    - kaleido
    - gdown
    - causal-learn
    - langchain_community
    - langchain
    - langchain_core
    - langchain_huggingface
    - transformers>=4.35,<4.47
    - accelerate>=0.26.0
    - bnlearn==0.12.0
    - pgmpy==0.1.25
    - nltk
    - mistralai
    - openai
    - requests
    - beautifulsoup4
    - lxml
    - duckduckgo_search
    - flwr
    - opacus
    - seaborn
    - SciencePlots
    - torchxrayvision
