defaults:
  - default
  - _self_

client_id: 1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      # possible datsets are:
      # colormnist, colormnist_ood, celeba, celeba_unfair, siim_pneumothorax
      # asia, sachs, alarm, hailfinder, insurance
      seed: 1 #, 2, 3, 4, 5
      dataset: asia #, asia # asia, sachs, alarm
      # possible models are:
      # blackbox, blackbox_multi, cbm_linear, cbm_mlp, cem, c2bm
      model: blackbox_multi, c2bm #, cbm_linear, cbm_mlp, cem, c2bm #, cem, c2bm #, cbm_linear, cbm_mlp, cem, c2bm
      learning: localized, centralized, local_federated #, centralized #, centralized, local_federated, federated
      
model:
  hidden_size: 128

dataset:
  load_embeddings: false # disable when sweeping over different seeds
  load_graph: false
  load_true_graph: true
  batch_size: 128
  autoencoder:
   noise: 0.5  # for bndatasets only

engine:
  intervention_prob: 0.8
  test_interv_noise: 0.9   # for bndatasets only
  optim_kwargs:
    lr: 0.00075

trainer:
  # logger: wandb
  devices: [0]
  max_epochs: 10
  patience: 30

rag:
  verbose: false

notes: test_run
