defaults:
  - default
  - _self_

client_id: 1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      # possible datsets are: asia, sachs, alarm, hailfinder, insurance
      seed: 2, 3 #1, 2, 3, 4, 5
      dataset: asia, sachs #, alarm, insurance, hailfinder
      # possible models are:
      # blackbox, blackbox_multi, cbm_linear, cbm_mlp, cem, c2bm
      model: blackbox_multi, cbm_linear, cem, c2bm 
      learning: localized, centralized, local_federated 
      
model:
  hidden_size: 128

dataset:
  load_embeddings: true 
  load_graph: false
  load_true_graph: true
  batch_size: 128
  autoencoder:
   noise: 0.5  # for bndatasets only

engine:
  intervention_prob: 0.8
  test_interv_noise: 0.9   # for bndatasets only
  optim_kwargs:
    lr: 0.00075

trainer:
  # logger: wandb
  devices: [0]
  max_epochs: 500
  patience: 30

rag:
  verbose: false

notes: test_run