
_target_: "src.models.blackbox_multioutput.BlackBox_Multi"
hidden_size: ${dataset.hidden_size}
n_layers_encoder: 2
n_layers_decoder: 1
activation: leaky_relu
concept_loss_weight: 0.5
name: "blackbox_multi"